name: on pull request

on:
#todo replace by on pull request fire event
  push:

env:
  node-version: 16
  
jobs:

  install:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Install dependencies
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app node:16 npm install
    - name: zip up dependencies
      run:  zip -r dependency.zip ${{ github.workspace }}/node_modules
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: node-modules
        path: ${{ github.workspace }}/dependency.zip
        
  build:
    needs: install
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: node-modules
        path: ${{ github.workspace }}/dependency.zip
        
    - name: Build
      run: |
        ls
        unzip *.zip
        ls
        docker run -v ${{ github.workspace }}:/app -w /app node:16 npm run build
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ github.workspace }}/dist
        
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: node-modules
        path: ${{ github.workspace }}/dependency.zip
        
    - name: Test
      run: |
        unzip -o ${{ github.workspace }}/dependency.zip -d ${{ github.workspace }}
        docker run -v ${{ github.workspace }}:/app -w /app node:16 npm test


  eslint:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: node-modules
        path: ${{ github.workspace }}/dependency.zip
        
    - name: eslint
      run: |
        unzip -o ${{ github.workspace }}/dependency.zip -d ${{ github.workspace }}
        docker run -v ${{ github.workspace }}:/app -w /app node:16 npm lint



