name: on pull request

on:
#todo replace by on pull request fire event
  push:

env:
  node-version: 20
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Install dependencies
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app node:20 npm install
    - name: build app
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app node:20 npm run build
        

  
  test:
    needs: install
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Install dependencies
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app node:20 npm install
    - name: build app
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app node:20 npm run test

  
  lint:
    needs: install
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Install dependencies
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app node:20 npm install
    - name: build app
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app node:20 npm run lint




